# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/logdb
#     username: root
#     password: root
#   jpa:
#     hibernate.ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect
#   activemq:
#     broker-url: tcp://localhost:61616

server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: admin